version: '2.1'
services:
   sql-client:
      user: flink:flink
      build: .
      command: bin/sql-client.sh embedded -j /opt/flink/hudi-flink1.17-bundle-0.14.1.jar shell
      depends_on:
         - jobmanager
         - postgres
      environment:
         - POSTGRES_HOST=postgres
         - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
            rest.address: jobmanager                       
      volumes:
        - ./data/hudi/:/tmp/hudi_hudi_table
   jobmanager:
      user: flink:flink
      build: .
      ports:
         - "8081:8081"
      command: jobmanager
      environment:
         - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager            
      volumes:
         - ./data/hudi/:/tmp/hudi_hudi_table
   taskmanager:
      user: flink:flink
      build: .
      depends_on:
         - jobmanager
      command: taskmanager
      environment:
         - |
            FLINK_PROPERTIES=
            jobmanager.rpc.address: jobmanager
            taskmanager.numberOfTaskSlots: 2            
      volumes:
         - ./data/hudi/:/tmp/hudi_hudi_table
   postgres_deb:
     image: debezium/example-postgres:1.1
     ports:
       - "5432:5432"
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
   postgres:
     image: postgres:15.2
     ports:
       - "5433:5432"
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
     command:    
       - "postgres"
       - "-c"
       - "wal_level=logical"
volumes:
   shared-tmpfs:
     driver: local
     driver_opts:
       type: "tmpfs"
       device: "tmpfs"
